import {
  BookOpen,
  BriefcaseBusiness,
  CreditCard,
  Globe2,
  GraduationCap,
  Heart,
  IdCard,
  KeyRound,
  Link2,
  StickyNote,
  ShieldCheck,
  ShoppingBag,
} from "lucide-react";
import type { AppUser, SectionDefinition, SectionId, VaultItem } from "./types";

export const DEMO_USER: AppUser = {
  id: "demo-amina",
  email: "amina@persora.demo",
  fullName: "Amina Rahman",
  role: "user",
  timezone: "Asia/Dhaka",
  demo: true,
};

export const SECTION_DEFINITIONS: SectionDefinition[] = [
  {
    id: "documents",
    label: "Documents",
    eyebrow: "Personal vault",
    singular: "document",
    description: "Keep identity, health and important paperwork together, with expiry dates never out of sight.",
    icon: IdCard,
    color: "blue",
    titleLabel: "Document title",
    dateKey: "expiryDate",
    previewKeys: ["type", "documentNumber", "expiryDate"],
    fields: [
      { key: "title", label: "Document title", kind: "text", placeholder: "e.g. Bangladesh passport", required: true },
      { key: "type", label: "Document type", kind: "select", options: ["National ID / NID", "Passport", "Birth certificate", "Student ID", "Job ID / Employee ID", "Driving licence", "Tax ID / TIN", "Visa", "Residence permit", "Work permit", "Health card", "Insurance", "Certificate", "Contract", "CV / Resume", "Other"], required: true },
      { key: "documentNumber", label: "Document number", kind: "text", placeholder: "Optional" },
      { key: "issueDate", label: "Issue date", kind: "date" },
      { key: "expiryDate", label: "Expiry date", kind: "date" },
      { key: "member", label: "Belongs to", kind: "select", options: ["Me", "Spouse", "Father", "Mother", "Child", "Sibling", "Other"] },
      { key: "targetRole", label: "Target role", kind: "text", placeholder: "e.g. Product Designer" },
      { key: "email", label: "Contact email", kind: "email" },
      { key: "phone", label: "Phone", kind: "text" },
      { key: "location", label: "Location", kind: "text", placeholder: "City, country" },
      { key: "portfolio", label: "LinkedIn / portfolio", kind: "url", placeholder: "https://" },
      { key: "summary", label: "Professional summary", kind: "textarea", wide: true },
      { key: "experience", label: "Experience", kind: "textarea", wide: true },
      { key: "education", label: "Education", kind: "textarea", wide: true },
      { key: "skills", label: "Skills", kind: "textarea", wide: true },
      { key: "notes", label: "Notes", kind: "textarea", placeholder: "Add a reminder or any useful details", wide: true },
    ],
  },
  {
    id: "academics",
    label: "Academics",
    eyebrow: "Education records",
    singular: "academic record",
    description: "Build a tidy archive of certificates, transcripts, results and the milestones behind them.",
    icon: GraduationCap,
    color: "violet",
    titleLabel: "Record title",
    previewKeys: ["type", "institution", "year"],
    fields: [
      { key: "title", label: "Record title", kind: "text", placeholder: "e.g. BSc in Computer Science", required: true },
      { key: "type", label: "Record type", kind: "select", options: ["SSC / Secondary certificate", "HSC / Higher secondary certificate", "Diploma", "Bachelor's degree", "Master's degree", "PhD", "Mark sheet", "Transcript", "Certificate", "Admission record", "Admission letter", "Admission payment slip", "Admission application", "Exam document", "Training record", "Other"], required: true },
      { key: "institution", label: "Institution", kind: "text", placeholder: "School, college or university" },
      { key: "year", label: "Year completed", kind: "text", placeholder: "e.g. 2024" },
      { key: "grade", label: "Grade / result", kind: "text", placeholder: "Optional" },
      { key: "program", label: "Program / course", kind: "text", placeholder: "e.g. BSc in Computer Science" },
      { key: "admissionSession", label: "Admission session", kind: "text", placeholder: "e.g. Fall 2026" },
      { key: "applicationNumber", label: "Application / student ID", kind: "text" },
      { key: "paymentAmount", label: "Payment amount", kind: "text", placeholder: "e.g. ৳ 15,000" },
      { key: "paymentDate", label: "Payment date", kind: "date" },
      { key: "notes", label: "Notes", kind: "textarea", wide: true },
    ],
  },
  {
    id: "subscriptions",
    label: "Subscriptions",
    eyebrow: "Recurring expenses",
    singular: "subscription",
    description: "See what renews, what it costs and which payment method is attached to every plan.",
    icon: CreditCard,
    color: "orange",
    titleLabel: "Service name",
    dateKey: "renewalDate",
    previewKeys: ["plan", "price", "renewalDate"],
    fields: [
      { key: "title", label: "Service name", kind: "text", placeholder: "e.g. Spotify", required: true },
      { key: "plan", label: "Plan", kind: "text", placeholder: "e.g. Individual" },
      { key: "price", label: "Price", kind: "text", placeholder: "e.g. ৳ 219 / month" },
      { key: "cycle", label: "Billing cycle", kind: "select", options: ["Monthly", "Quarterly", "Yearly", "Weekly", "One-time", "Other"] },
      { key: "startDate", label: "Start date", kind: "date" },
      { key: "renewalDate", label: "Next renewal", kind: "date" },
      { key: "payment", label: "Payment method", kind: "text", placeholder: "e.g. Visa •••• 4821" },
      { key: "accountEmail", label: "Account email", kind: "email", placeholder: "name@example.com" },
      { key: "website", label: "Login website", kind: "url", placeholder: "https://" },
      { key: "notes", label: "Notes", kind: "textarea", wide: true },
    ],
  },
  {
    id: "family",
    label: "Family",
    eyebrow: "Family records",
    singular: "family member",
    description: "Keep the people you care about connected to the documents and details that matter to them.",
    icon: Heart,
    color: "rose",
    titleLabel: "Full name",
    previewKeys: ["relationship", "dateOfBirth", "notes"],
    fields: [
      { key: "title", label: "Full name", kind: "text", placeholder: "e.g. Samira Rahman", required: true },
      { key: "relationship", label: "Relationship", kind: "select", options: ["Spouse", "Father", "Mother", "Child", "Brother / Sister", "Grandparent", "Other"] },
      { key: "dateOfBirth", label: "Date of birth", kind: "date" },
      { key: "email", label: "Email", kind: "email", placeholder: "Optional" },
      { key: "phone", label: "Phone", kind: "text", placeholder: "Optional" },
      { key: "notes", label: "Notes", kind: "textarea", placeholder: "Important context or reminders", wide: true },
    ],
  },
  {
    id: "purchases",
    label: "Purchases & warranty",
    eyebrow: "Purchase vault",
    singular: "purchase record",
    description: "Invoices, serial numbers and warranty dates—right where you can find them when you need them.",
    icon: ShoppingBag,
    color: "teal",
    titleLabel: "Product name",
    dateKey: "warrantyExpiry",
    previewKeys: ["brand", "purchaseDate", "warrantyExpiry"],
    fields: [
      { key: "title", label: "Product name", kind: "text", placeholder: "e.g. MacBook Air 15-inch", required: true },
      { key: "brand", label: "Brand", kind: "text" },
      { key: "model", label: "Model", kind: "text" },
      { key: "serial", label: "Serial / IMEI", kind: "text" },
      { key: "seller", label: "Seller / store", kind: "text" },
      { key: "purchaseDate", label: "Purchase date", kind: "date" },
      { key: "price", label: "Purchase price", kind: "text", placeholder: "e.g. ৳ 145,000" },
      { key: "invoiceNumber", label: "Invoice number", kind: "text" },
      { key: "warrantyExpiry", label: "Warranty expires", kind: "date" },
      { key: "notes", label: "Notes", kind: "textarea", wide: true },
    ],
  },
  {
    id: "accounts",
    label: "Internet accounts",
    eyebrow: "Account index",
    singular: "account",
    description: "A private index of important online accounts, sign-in links and the details you always forget.",
    icon: KeyRound,
    color: "indigo",
    titleLabel: "Service name",
    previewKeys: ["accountType", "username", "email"],
    fields: [
      { key: "title", label: "Service name", kind: "text", placeholder: "e.g. Google", required: true },
      { key: "accountType", label: "Account type", kind: "select", options: ["Facebook", "Instagram", "LinkedIn", "X", "TikTok", "YouTube", "WhatsApp", "Telegram", "GitHub", "Pinterest", "Google", "Gmail", "Microsoft", "Apple", "Amazon", "Netflix", "Spotify", "Discord", "Reddit", "PayPal", "Email", "Social media", "Banking / payments", "Shopping", "Education", "Freelance", "Work", "Cloud services", "Developer", "Gaming", "Streaming", "Government", "Business", "Other"] },
      { key: "username", label: "Username", kind: "text" },
      { key: "email", label: "Account email", kind: "email" },
      { key: "website", label: "Login URL", kind: "url", placeholder: "https://" },
      { key: "registered", label: "Registration date", kind: "date" },
      { key: "status", label: "Account status", kind: "select", options: ["Active", "Paused", "Closed", "Review needed"] },
      { key: "notes", label: "Important notes", kind: "textarea", wide: true },
    ],
  },
  {
    id: "memberships",
    label: "Membership wallet",
    eyebrow: "Digital wallet",
    singular: "membership",
    description: "Keep membership IDs, loyalty cards and renewal dates ready in one digital wallet.",
    icon: CreditCard,
    color: "green",
    titleLabel: "Membership name",
    dateKey: "expiryDate",
    previewKeys: ["organization", "memberId", "expiryDate"],
    fields: [
      { key: "title", label: "Membership name", kind: "text", placeholder: "e.g. City Library", required: true },
      { key: "type", label: "Membership type", kind: "select", options: ["Gym", "Library", "Student", "Professional", "Club", "Loyalty", "Retail", "Travel", "Insurance", "Gaming", "Event", "Community", "Other"] },
      { key: "organization", label: "Organization", kind: "text" },
      { key: "memberId", label: "Member ID / card number", kind: "text" },
      { key: "startDate", label: "Start date", kind: "date" },
      { key: "expiryDate", label: "Expiry date", kind: "date" },
      { key: "level", label: "Membership level", kind: "text", placeholder: "e.g. Gold" },
      { key: "website", label: "Website", kind: "url", placeholder: "https://" },
      { key: "notes", label: "Notes", kind: "textarea", wide: true },
    ],
  },
  {
    id: "study",
    label: "Study materials",
    eyebrow: "Study space",
    singular: "study material",
    description: "Bring notes, books, lecture slides and saved links into one searchable study space.",
    icon: BookOpen,
    color: "sky",
    titleLabel: "Material name",
    previewKeys: ["course", "subject", "materialType"],
    fields: [
      { key: "title", label: "Material name", kind: "text", placeholder: "e.g. Week 04 — Color systems", required: true },
      { key: "course", label: "Course", kind: "text" },
      { key: "subject", label: "Subject", kind: "text" },
      { key: "chapter", label: "Chapter / topic", kind: "text" },
      { key: "materialType", label: "Material type", kind: "select", options: ["PDF", "Notes", "Lecture slides", "Book", "Document", "Image", "Audio", "Video", "Assignment", "Question paper", "Solution", "Research paper", "Link", "Personal notes"] },
      { key: "semester", label: "Semester / year", kind: "text" },
      { key: "tags", label: "Tags", kind: "text", placeholder: "Separate tags with commas" },
      { key: "notes", label: "Notes", kind: "textarea", wide: true },
    ],
  },
  {
    id: "notes",
    label: "Tasks & Notes",
    eyebrow: "Tasks, notes & reminders",
    singular: "note",
    description: "Keep tasks moving, set reminders and alarms, and save thoughts in one private, searchable space.",
    icon: StickyNote,
    color: "yellow",
    titleLabel: "Note title",
    previewKeys: ["tags"],
    fields: [
      { key: "title", label: "Note title", kind: "text", placeholder: "e.g. Ideas for the weekend", required: true },
      { key: "content", label: "Note", kind: "textarea", placeholder: "Write your note here…", wide: true },
      { key: "tags", label: "Tags", kind: "text", placeholder: "Separate tags with commas", wide: true },
    ],
  },
  {
    id: "business-card",
    label: "Digital business card",
    eyebrow: "Your digital identity",
    singular: "digital card",
    description: "A polished, shareable profile for the moments you want to make a great introduction.",
    icon: BriefcaseBusiness,
    color: "slate",
    titleLabel: "Full name",
    previewKeys: ["jobTitle", "company", "email"],
    fields: [
      { key: "title", label: "Full name", kind: "text", placeholder: "Your name", required: true },
      { key: "jobTitle", label: "Job title", kind: "text" },
      { key: "company", label: "Company", kind: "text" },
      { key: "bio", label: "Short bio", kind: "textarea", wide: true },
      { key: "phone", label: "Phone", kind: "text" },
      { key: "email", label: "Email", kind: "email" },
      { key: "website", label: "Website", kind: "url", placeholder: "https://" },
      { key: "linkedin", label: "LinkedIn", kind: "url", placeholder: "https://linkedin.com/in/…" },
      { key: "instagram", label: "Instagram", kind: "url", placeholder: "https://instagram.com/…" },
      { key: "location", label: "Location", kind: "text" },
    ],
  },
  {
    id: "urls",
    label: "URL manager",
    eyebrow: "Quick links",
    singular: "saved URL",
    description: "The useful links you never want to search for twice, neatly organized and ready to open.",
    icon: Link2,
    color: "cyan",
    titleLabel: "Link name",
    previewKeys: ["urlCategory", "url", "tags"],
    fields: [
      { key: "title", label: "Link name", kind: "text", placeholder: "e.g. Portfolio", required: true },
      { key: "url", label: "URL", kind: "url", placeholder: "https://example.com", required: true },
      { key: "urlCategory", label: "Category", kind: "select", options: ["Personal website", "Portfolio", "Social profile", "LinkedIn", "GitHub", "YouTube", "Payment link", "Business", "Booking", "Government portal", "Job portal", "Education portal", "Other"] },
      { key: "owner", label: "Owner / service", kind: "text" },
      { key: "tags", label: "Tags", kind: "text", placeholder: "Separate tags with commas" },
      { key: "description", label: "Description", kind: "textarea", wide: true },
      { key: "notes", label: "Notes", kind: "textarea", wide: true },
    ],
  },
];

export const SECTION_BY_ID = Object.fromEntries(SECTION_DEFINITIONS.map((section) => [section.id, section])) as Record<SectionId, SectionDefinition>;

const now = new Date().toISOString();
const item = (id: string, section: SectionId, title: string, metadata: Record<string, string>, file?: VaultItem["file"]): VaultItem => ({
  id,
  section,
  title,
  metadata,
  createdAt: now,
  updatedAt: now,
  ...(file ? { file } : {}),
});

export const INITIAL_ITEMS: VaultItem[] = [
  item("doc-passport", "documents", "Bangladesh passport", { type: "Passport", documentNumber: "EA 0864 219", issueDate: "2021-11-06", expiryDate: "2026-10-14", member: "Me", notes: "Renewal appointment to be booked." }, { name: "passport-scan.pdf", size: 2480000, type: "application/pdf", localOnly: true }),
  item("doc-nid", "documents", "National ID card", { type: "National ID / NID", documentNumber: "1998 •••• 3412", issueDate: "2017-04-12", expiryDate: "", member: "Me", notes: "Front and back scan." }, { name: "nid-front.jpg", size: 840000, type: "image/jpeg", localOnly: true }),
  item("doc-birth", "documents", "Birth certificate", { type: "Birth certificate", documentNumber: "1998 26 1047 38291", issueDate: "1998-02-18", expiryDate: "", member: "Me", notes: "Digital copy verified." }),
  item("doc-health", "documents", "Family health insurance", { type: "Insurance", documentNumber: "POL-3409-1182", issueDate: "2025-05-01", expiryDate: "2027-05-01", member: "Family", notes: "Renewal is annual." }),
  item("acad-bsc", "academics", "BSc in Computer Science", { type: "Bachelor's degree", institution: "North South University", year: "2023", grade: "CGPA 3.76", notes: "Final transcript and certificate." }, { name: "bsc-transcript.pdf", size: 4280000, type: "application/pdf", localOnly: true }),
  item("acad-hsc", "academics", "HSC transcript", { type: "HSC / Higher secondary certificate", institution: "Viqarunnisa Noon College", year: "2019", grade: "GPA 5.00", notes: "Science group." }),
  item("acad-ux", "academics", "Product design certificate", { type: "Training record", institution: "Interaction Design Foundation", year: "2024", grade: "Distinction", notes: "Completed six courses." }),
  item("sub-spotify", "subscriptions", "Spotify Premium", { plan: "Individual", price: "৳ 219 / month", cycle: "Monthly", renewalDate: "2026-10-06", payment: "Visa •••• 4821", accountEmail: "amina.rahman@email.com", website: "https://spotify.com", notes: "Student plan ended last year." }),
  item("sub-google", "subscriptions", "Google One", { plan: "Premium · 2 TB", price: "৳ 650 / month", cycle: "Monthly", renewalDate: "2026-10-18", payment: "bKash", accountEmail: "amina.rahman@email.com", website: "https://one.google.com", notes: "Family sharing enabled." }),
  item("sub-netflix", "subscriptions", "Netflix", { plan: "Standard", price: "৳ 799 / month", cycle: "Monthly", renewalDate: "2026-10-22", payment: "Visa •••• 4821", accountEmail: "amina.rahman@email.com", website: "https://netflix.com", notes: "Household plan." }),
  item("sub-adobe", "subscriptions", "Adobe Creative Cloud", { plan: "Photography", price: "৳ 1,150 / month", cycle: "Monthly", renewalDate: "2026-11-02", payment: "Visa •••• 4821", accountEmail: "amina.rahman@email.com", website: "https://account.adobe.com", notes: "Annual plan, billed monthly." }),
  item("fam-samira", "family", "Samira Rahman", { relationship: "Mother", dateOfBirth: "1967-08-11", email: "", phone: "+880 1712 450 188", notes: "Emergency contact" }),
  item("fam-rayan", "family", "Rayan Rahman", { relationship: "Brother / Sister", dateOfBirth: "2002-03-24", email: "rayan.r@email.com", phone: "", notes: "University student" }),
  item("purchase-mac", "purchases", "MacBook Air 15-inch", { brand: "Apple", model: "M3 · 16 GB / 512 GB", serial: "C02 •••• H7Y3", seller: "Gadget & Gear", purchaseDate: "2025-02-09", price: "৳ 184,000", invoiceNumber: "GG-25-02139", warrantyExpiry: "2027-02-09", notes: "AppleCare+ coverage." }, { name: "macbook-invoice.pdf", size: 1380000, type: "application/pdf", localOnly: true }),
  item("purchase-phone", "purchases", "iPhone 15", { brand: "Apple", model: "128 GB · Blue", serial: "G6T •••• JQ1", seller: "Apple Gadgets", purchaseDate: "2024-06-21", price: "৳ 119,999", invoiceNumber: "AG-48102", warrantyExpiry: "2025-06-21", notes: "Warranty expired." }),
  item("purchase-camera", "purchases", "Fujifilm X-S20", { brand: "Fujifilm", model: "X-S20 body", serial: "4A •••• 9081", seller: "Camera World", purchaseDate: "2026-01-15", price: "৳ 149,000", invoiceNumber: "CW-019882", warrantyExpiry: "2027-01-15", notes: "Keep original box." }),
  item("acct-github", "accounts", "GitHub", { accountType: "Developer", username: "aminarahman", email: "amina.rahman@email.com", website: "https://github.com", registered: "2018-05-04", status: "Active", notes: "Passkey enabled." }),
  item("acct-linkedin", "accounts", "LinkedIn", { accountType: "Social media", username: "amina-rahman-design", email: "amina.rahman@email.com", website: "https://linkedin.com", registered: "2019-01-22", status: "Active", notes: "Work profile." }),
  item("acct-bank", "accounts", "City Bank Online", { accountType: "Banking / payments", username: "amina.r•••", email: "amina.rahman@email.com", website: "https://citytouch.com.bd", registered: "2020-07-13", status: "Active", notes: "Never store your password here." }),
  item("mem-library", "memberships", "British Council Library", { type: "Library", organization: "British Council Bangladesh", memberId: "BC-2409-6811", startDate: "2024-07-01", expiryDate: "2026-12-31", level: "Digital member", website: "https://www.britishcouncil.org.bd", notes: "Renew online." }),
  item("mem-gym", "memberships", "Gulshan Club Fitness", { type: "Gym", organization: "Gulshan Club", memberId: "GC-882014", startDate: "2025-04-01", expiryDate: "2026-09-30", level: "Gold", website: "", notes: "Monthly renewal." }),
  item("study-color", "study", "Color systems & accessibility", { course: "Product Design Foundations", subject: "Visual design", chapter: "Week 04", materialType: "Lecture slides", semester: "Spring 2026", tags: "design, accessibility", notes: "Review WCAG contrast examples." }, { name: "color-systems.pdf", size: 3280000, type: "application/pdf", localOnly: true }),
  item("study-research", "study", "Usability testing checklist", { course: "Independent learning", subject: "Research", chapter: "Field guide", materialType: "Notes", semester: "2026", tags: "research, ux", notes: "Use for next discovery sprint." }),
  item("study-data", "study", "SQL for product analytics", { course: "Data for designers", subject: "Analytics", chapter: "Joins & funnels", materialType: "Link", semester: "2026", tags: "sql, analytics", notes: "Continue from lesson 7." }),
  item("business-card-main", "business-card", "Amina Rahman", { jobTitle: "Product Designer", company: "Northstar Studio", bio: "Designing calm, useful digital products for people and teams.", phone: "+880 1712 450 188", email: "amina.rahman@email.com", website: "https://amina.design", linkedin: "https://linkedin.com/in/amina-rahman-design", instagram: "", location: "Dhaka, Bangladesh" }),
  item("url-portfolio", "urls", "Portfolio website", { url: "https://amina.design", urlCategory: "Portfolio", owner: "Amina Rahman", tags: "work, design", description: "Selected product design work and case studies.", notes: "Updated June 2026." }),
  item("url-notion", "urls", "Design reading list", { url: "https://notion.so", urlCategory: "Personal website", owner: "Notion", tags: "reading, design", description: "Articles and books to come back to.", notes: "Shared with work email." }),
  item("url-gov", "urls", "NID services", { url: "https://services.nidw.gov.bd", urlCategory: "Government portal", owner: "Bangladesh Election Commission", tags: "government, identity", description: "Official NID services portal.", notes: "Use the bookmark, not search ads." }),
  item("url-calendar", "urls", "Appointment calendar", { url: "https://calendar.google.com", urlCategory: "Business", owner: "Google", tags: "calendar, work", description: "Work and personal calendar.", notes: "" }),
];

export const NAV_GROUPS: { label: string; ids: SectionId[] }[] = [
  { label: "Personal life", ids: ["documents", "academics", "family"] },
  { label: "Everyday", ids: ["subscriptions", "purchases", "accounts", "memberships"] },
  { label: "Knowledge & identity", ids: ["study", "notes", "business-card", "urls"] },
];

export const BRAND_ICON = ShieldCheck;
export const GLOBE_ICON = Globe2;
